Shopify/shopify_python

.travis.yml
Makefile
setup.py
tests/shopify_python/test_package.py

This PR adds support for Travis CI including:
- Python 2.7, 3.3, 3.4, 3.5, and 3.6
- Pylint on all Python versions
- Mypy Python 2-compatible type annotation checking for Python 3.x only
To accomplish this, a modern requirement specifier was used in `setup.py`'s`extras_require` which necessitated upgrading `setuptools` on Travis CI.

Add Travis CI support

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

This syntax for re-raising exceptions with context is acceptable, and shouldn't raise a linter error.
@cfournie

Exception false negative

---

README.md

For projects, including those one, we should follow a standard version numbering scheme. For simplicity, let's use [Semantic Versioning 2.0.0](http://semver.org/spec/v2.0.0.html).

Follow semantic versioning 2.0.0

---

setup.py
shopify_python/__init__.py
shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

On a Python 3.5 project, when applying the `import-modules-only` rule its call to `importlib.util.find_spec` was returning `None` for modules (but not packages) when linting, but their parent packages succeeded, causing them to look like they were unimportable children of a module (i.e. probably a function/class).
This PR:
- Alters how import checks are perfomed; instead of relying upon the various implementations of `importlib` available this borrows functionality used by the [pylint F0401 "Unable to import %s" ](https://github.com/PyCQA/pylint/blob/7df8caaa3e1995018417ac2fd87afd89be6945ba/pylint/checkers/imports.py#L603) check to [search for and parse the AST of the file described by the import](https://github.com/PyCQA/astroid/blob/ac3e82e9bd8678086325a71a927a06bbc43d415e/astroid/manage …

Fix import-module-only check

---

shopify_python/google_styleguide.py

Pylint already has rules for some of the elements in the Google Python Styleguide, so let's document that.

Document already-handled rules

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

This PR lessens the restrictions on global vars to allow:
- Any dunder-var (e.g. `__version__`);
- Any uppercase variable that is assigned a constant (e.g. `CONSTANT_NAME = 10`); and
- Any class-name-style variable assignment (to allow `namedtuple` and other type declarations).

Allow global vars that are constants or type definitions

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

This PR lessens the restrictions on global constants to allow the assignment of any type of object.
[> If the developer uses a naming convention to tell other developers that it's a const, we should believe them.](https://github.com/Shopify/shopify_python/pull/14#discussion_r104935752)

Allow all assignment types to global constants

---

shopify_python/__init__.py

Let's cut a bugfix release that adds these PRs:
- Document already-handled rules https://github.com/Shopify/shopify_python/pull/11
- Allow global vars that are constants or type definitions https://github.com/Shopify/shopify_python/pull/14
- Allow all assignment types to global constants https://github.com/Shopify/shopify_python/pull/16

Bump version to 1.1.2

---

shopify_python/ast.py
shopify_python/google_styleguide.py
tests/shopify_python/test_ast.py
tests/shopify_python/test_google_styleguide.py

This PR tries to measure the complexity of `try`/`except`/`finally` blocks in terms of the number of AST nodes within the body of each statement. The goal of these rules is to encourage less code (not simply measured in lines) within these sections.
> The larger the body of the try, the more likely that an exception will be raised by a line of code that you didn't expect to raise an exception. In those cases, the try/except block hides a real error. 
– Google Python Styleguide
Running this on a large codebase we get no parse errors and by setting the max length to zero we also get some statistics on body tree sizes in nodes:
| 	| Try	| Except	| Finally
|----|------|-----------|--------
| Count	| 122	| 126	| 12
| 90th precentile	| 40.8	| 33	| 15.7
| 80th precentile	| 24.8	| 23	| 12.8
| …

Add try/except/finally complexity rules

---

README.md

Version numbers are only really useful for libraries that are used in other projects. Applications don't need to be versioned (especially if they are continuously deployed).

Not everyone needs to use version numbers

---

shopify_python/google_styleguide.py

This PR rephrases the help messages to remove formatting elements. This changes:
```
$ pylint --help-msg C2601
:import-modules-only (C2601): *%(child)s is not a module or cannot be imported*
Install %(child)s or only import packages or modules from it This message
belongs to the google-styleguide-checker checker.
```
To now read:
```
$ pylint --help-msg C2601
:import-modules-only (C2601): *%(child)s is not a module or cannot be imported*
Only import packages or modules and ensure that they are installed. This message
belongs to the google-styleguide-checker checker.
```

Help messages don't support formatting

---

pylintrc

I find 30 characters for a function or method name way too short, particularly for descriptive test method names. What do you think of 90?
@cfournie @erikwright ?

increase maximum length of function and method names

---

pylintrc

This PR makes the pylint output much more readable in my opinion.
Current master
This PR:
This PR, without being colorized:
Thoughts? @cfournie @honkfestival

change pylint output format

---

setup.py
shopify_python/git_utils.py
tests/shopify_python/test_git_utils.py

We commonly use an untested script, copied from one repo to another, as a git push hook to automatically autopep, lint, and (sometimes) type-check on the modified files prior to pushing to GitHub. Let's pull that into tested utilities.
First step is a utility to compare what is being pushed to what is on `origin/master`. This utility function uses what has been _committed_ in the current branch (not added to the index, or untracked files), and compares it to `origin/master`. Any files that have been added or modified will be returned, provided they are also Python files or scripts.
~~There are a couple of unrelated changes that are also in other PRs (`.gitignore` and `pylintrc` file changes). I'll rebase this PR after those merge.~~
@cfournie @erikwright @honkfestival ?

Utility to detect changed python files

---

Makefile
setup.py
shopify_python/git_utils.py

Because on Travis CI we're executing this makefile with `sh` (which doesn't support `==` comparisons), we were skipping type annotation checking and make returns:
```
/bin/sh: 1: [: 3: unexpected operator
```
This PR fixes this issue, a type annotation issue, and installs `mypy` for Python 3.3 because it was missing.

Missing type annotation

---

setup.py
shopify_python/__init__.py
shopify_python/shopify_styleguide.py
tests/shopify_python/test_shopify_styleguide.py

This PR adds a check to ensure that source code disables rules by message name and not message code. Fixes https://github.com/Shopify/shopify_python/issues/32.
If a bad message code is mentioned in a disable comment, in addition to `bad-option-value` we output a message suggesting `unknown` as a code (in case `bad-option-value` has been disabled):
```
shopify_python/shopify_styleguide.py:3:0 E0012(bad-option-value) Bad option value 'X9999'
shopify_python/shopify_styleguide.py:3:0 C6101(disable-name-only) X9999 disabled as a message code, use 'unknown' instead
```

Check that we disable pylint messages by name and not code

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

This PR introduces a new import check, restricting imports to one import per line:
```
from foo import bar  # OK
from foo import baz # OK
from foo import bar, baz  # forbidden
```
This PR also ran up against other rule checks, so I created a new assertion checker that allows you to limit which codes are verified. This makes tests less fragile (no interdependencies between codes). Also, consumers may disable individual codes, so it's important that we test a code in isolation, whether or not it also fails other checks.
@cfournie @honkfestival

add new check for multiple imports

---

shopify_python/git_utils.py
shopify_python/google_styleguide.py
tests/shopify_python/test_git_utils.py
tests/shopify_python/test_google_styleguide.py

Lambdas can be very useful but they are "[h]arder to read and debug than local functions. The lack of names means stack traces are more difficult to understand. Expressiveness is limited because the function may only contain an expression."
To limit need to debug lambdas let's encourage them to be simple and to have a maximum number os AST nodes. The default of 15 was chosen arbitrarily.

Use simple lambdas

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

"Complicated list comprehensions or generator expressions can be hard to read." To encourage simple list comprehensions let's limit them to using one `for` statement each.

Restrict list comprehension complexity

---

shopify_python/__init__.py
shopify_python/google_styleguide.py

This PR proposes a bugfix release (v0.2.1) and fixes a mismatch between a message name added versus defined (`__use_simple_lambdas` adds `use-simple-lambdas` whereas `C6011` was defined as `lambda-too-long`).
A test to prevent this should be added in the future https://github.com/Shopify/shopify_python/issues/45.
Fixes https://github.com/Shopify/shopify_python/issues/43.

Fix message name and increase version to 0.2.1

---

shopify_python/__init__.py
shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

https://github.com/Shopify/shopify_python/pull/44 didn't fix the missing formatting constant.
We need integration tests https://github.com/Shopify/shopify_python/issues/45.

Fix missing formatting constant value and increase version to v0.2.2

---

pylintrc

This PR substitutes `C0111 ` with `missing-docstring` in `pylintrc` and adds an explanation as to why.

Disable by msg name not code in pylintrc

---

shopify_python/git_utils.py
tests/shopify_python/test_git_utils.py

This PR introduces a replacement for the "autopep" portion of the github pre-push hook. It's pretty simple, just calls the `autopep8.fix_multiple_files` with appropriate options to fix files in-place, using the same settings as starscream and data_bang currently use.
I've made the interface a little more generic so we can choose to expose additional options in the future if necessary.
@cfournie What do you think?

Add autopep utility

---

shopify_python/git_utils.py
tests/shopify_python/test_git_utils.py

Furthering the work to extract common functionality from `script/pre-push` files in various repos, this PR adds a simplified `pylint` interface for linting a passed list of files and/or directories.
It accepts all the "useful" command-line arguments, such as `rcfile`, `ignore`, and `msg-template`. If passed a path to a pylint configuration file, it will respect all customizations (ignored rules, message templates, regexes, etc). This allows this code to be used with a project's specific & customized configuration file.

add pylint utility

---

Makefile
setup.cfg
setup.py

[pep8 was renamed](http://pep8.readthedocs.io/en/release-1.7.x/) [pycodestyle](https://github.com/PyCQA/pycodestyle).

Replace pep8 with pycodestyle

---

shopify_python/git_utils.py
tests/shopify_python/test_git_utils.py

This PR addresses #53. Instead of diffing against remote master, first we use `merge_base` to determine the latest commit both branches (remote master, and the currently active branch) have. Then we diff against that.
This has the extra benefit of eliminating any files that have had net 0 changes (e.g. modified in one commit, then reverted in the second commit).
Tests updated to catch this situation explicitly.
@cfournie @damnMeddlingKid

improved modified files list

---

shopify_python/google_styleguide.py

Rule on https://github.com/Shopify/shopify_python/issues/36
It looks like pylint already covers semi-colons under two rules, `unncessary-semicolon` and `multiple-statements`

Semi-Colon

---

setup.py

1.7 was released and they changed some test utilities around and are [causing failures on master](https://travis-ci.org/Shopify/shopify_python/jobs/221730388).
This PR fixes this by temporarily pinning our pylint to pre 1.7.

Temporarily downgrade pylint

---

shopify_python/google_styleguide.py

One of the functional tests was failing because of a period in the `cond-expr` message that split the message into msg and confidence.
I'm replacing this period with a comma.

replaced period

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

Part of a rule on https://github.com/Shopify/shopify_python/issues/36
`simple-lambdas` has been implemented.
This PR is for preference of Operator Fcns over Lambda Fcns (https://google.github.io/styleguide/pyguide.html?showone=Lambda_Functions#Lambda_Functions)

prefer operator fncs to lambda fncs

---

setup.py
shopify_python/google_styleguide.py
shopify_python/shopify_styleguide.py
tests/shopify_python/test_google_styleguide.py

This PR bumps shopify_python to be compatible with Pylint 1.7.1 and up. I've explicitly dropped support for 1.6.5, let me know if you think we need to keep that in. The renaming of `pylint.utils.UnknownMessage` to `pylint.utils.UnknownMessageError` makes that a little more difficult.
Resolves https://github.com/Shopify/shopify_python/issues/68

bump to pylint 1.7.1

---

Makefile
setup.py

The latest version of setuptools (36.2.0) introduced https://github.com/pypa/setuptools/pull/1085, which disallows the manner in which we were specifying environment markers, which broke a variety of env marker usages https://github.com/pypa/setuptools/issues/1087.
This PR properly specifies env markers.

Change how we specify environment markers

---

RELEASING.md

[There are new URLs to use](https://docs.python.org/3.6/distutils/packageindex.html#the-pypirc-file), the old ones return HTTP 401 when trying to use them (as demonstrated while trying to release [v0.4.1](https://github.com/Shopify/shopify_python/releases/tag/v0.4.1))

Change release URLs

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

Fixes exception on the `is` keyword (https://github.com/Shopify/shopify_python/issues/77) by adding it to the list of operators.

Add support for 'is'

---

shopify_python/__init__.py

Let's cut a bugfix release that includes these bugfixes:
- Add support for 'is' keyword https://github.com/Shopify/shopify_python/pull/79

Increase version number to 0.4.2

---

RELEASING.md

Pinned the `__version__` link to a fixed commit and fixed `python setup.py register -r`'s URL (issue discovered while re-releasing [`pyoozie`](https://github.com/Shopify/pyoozie/releases/tag/v0.0.1); also see https://github.com/Shopify/pyoozie/pull/56).

Fix release notes

---

shopify_python/google_styleguide.py
tests/shopify_python/test_google_styleguide.py

We're [missing a few binary operators](https://docs.python.org/2/library/operator.html#mapping-operators-to-functions) and there are a few situations when `node.body.operand` doesn't have a name during the check for whether we can use an operator function as opposed to a lambda function, e.g.:
Linting `lambda key: not type_allowed(key._type)` throws
```
if operator and not isinstance(node.body.operand, astroid.BinOp) and argname is node.body.operand.name:
17 AttributeError: 'Call' object has no attribute 'name'
```
Linting `lambda key: not self.OUTPUT[key]["nullable"]` throws
```
if operator and not isinstance(node.body.operand, astroid.BinOp) and argname is node.body.operand.name:
17 AttributeError: 'Subscript' object has no attribute 'name'
```
Linting `lambda job: not job.is_loader` …

Fix lambda_func and operators

---

shopify_python/__init__.py

Let's cut a bugfix release that includes:
- Fix lambda_func and operators (https://github.com/Shopify/shopify_python/pull/83)

Increase version number to 0.4.3

---

shopify_python/google_styleguide.py
tests/functional/blank_line_after_class_required.py
tests/functional/blank_line_after_class_required.txt
tests/shopify_python/test_google_styleguide.py

Detect missing blank line after a class definition. (moved from starscream specific linter as suggested in https://github.com/Shopify/starscream/pull/21070)

Check for blank line after a class definition

---

setup.py

GitPython v2.1.8 has been released, and addresses an incompatibility with GitPython and git >= 2.15, which is now installed by default with brew.
@cfournie

bump GitPython to 2.1.8

---

.travis.yml
setup.py
shopify_python/git_utils.py

Fix the crash by providing the options `hang-closing` now required by Autopep8.
This option is actually passed to **pycodestyle**: 
```
--hang-closing       hang closing bracket instead of matching indentation of
opening bracket's line
```
See http://pycodestyle.pycqa.org/en/latest/intro.html
- Note 1: This PR **disables** this `hang-closing` option. ([discussion](https://github.com/PyCQA/pycodestyle/issues/103))
- Note 2: the commit to add tests in Py3.6 is here to trigger the CI and highlight the crash.
Resolves #90

Fix the crash on Autopep8 breaking change 

---

shopify_python/__init__.py

Maintenance release:
- Check for blank line after a class definition #86
- bump GitPython to 2.1.8 #87 
- Astroid less than 1.6 #89 
- Fix the crash on Autopep8 breaking change #91

Release v0.4.4

---

README.md

Just fixing it:
`compatbile` => `compatible`

Fix typo in readme: compatible

---

dev.yml

Make things easier for developing

Adds support for dev

---

Makefile
dev.yml
requirements.txt
setup.py

Resuming work on ShopifyPython is not easy without a proper dev setup.
- move the dev requirements from extra_require to a pip requirements file
- make Dev install the dev requirements
- make Dev install the project in develop mode

Better Dev support

---

setup.py

- Improve readability in install_requires with the [compatible-release](https://www.python.org/dev/peps/pep-0440/#compatible-release) constraints.
- Don't install `typing` when not needed

Improve readability for deps in setuptools install_requires

---

pylintrc
requirements.txt
setup.py
shopify_python/__init__.py
shopify_python/git_utils.py
shopify_python/google_styleguide.py
tests/functional/blank_line_after_class_required.py
tests/functional/global_variable.py
tests/functional/global_variable.txt
tests/functional/two_arg_exception3.txt
tests/shopify_python/test_google_styleguide.py
tests/shopify_python/test_shopify_styleguide.py

Pylint 2 seems to be a major overhaul. This PR fixes a few migration issues that arise.
It relies on some "private" parts of Pylint. I suggest that we should accept this for now but it would be appropriate to open a discussion with the maintainers about how to appropriately expose what we are looking for. I bumped the minor version number because it would seem that forcing clients to upgrade to a new version of Pylint is not really appropriate for a patch release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shopify/shopify_python/102)

Upgrade to Pylint 2

---

setup.py

After pushing to test PyPi, I found that when installed in Python3 the library would install PyLint 2.1.1 but it would also try (and fail) to install 1.9.3.
I traced it to an apparent bug in `wheel`, described here: https://github.com/inveniosoftware/troubleshooting/issues/1
Although some people imply that upgrading my build tools would also fix it, it seems more prudent to pick a mechanism that will work even if another maintainer happens to have a similar setup to mine (since there is nothing in the release steps that ensures that your pip/wheel/etc. are up-to-date).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shopify/shopify_python/103)

A more reliable way of having dependencies based on python_version.

---

shopify_python/__init__.py

I had to bump this because my original release of 0.5.0 (only ever uploaded to test PyPi) was broken and you cannot reuse a version even in the test repo.
I took the liberty of pushing the release already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shopify/shopify_python/104)

Bump version due to failed release in test PyPi.

---

requirements.txt
setup.py
shopify_python/__init__.py

When using `mypy`, to better deal with typing from dependent packages we need to "advertise" our support of typing. As it it describe at https://www.python.org/dev/peps/pep-0561/#packaging-type-information, if you want `mypy` to check for correct typing of dependant package and be able to ignore specific ones that don't support it, you need to add a specific marker in your `setup.py`.
This PR is adding the typing marker to the setup.py

Include typing marker for mypy (PEP-561).

---

requirements.txt
setup.py

The `typing` package became a part of the python library since Python 3.5, but was provisional up until 3.7. This PR gates the `typing` package to only be installed for python versions `< 3.7`.
As an aside, the tests were failing due to a change in an unpinned package dependency `astroid`. This PR also pins the astroid version to the last version that was passing tests.

Gate typing dependency

---

shopify_python/__init__.py

This bumps the package version to 0.5.3
This version accounts for changes made to the package dependencies which entail:
- gate `typing` package to `python_version < 3.5` to avoid pip installation failures in Python 3.7
- Pin `astroid` version to last version that passed our functional tests.
(https://github.com/Shopify/shopify_python/pull/112)

Bump version to 0.5.3

---

dev.yml
requirements.txt
shopify_python/__init__.py

Bumping shopify_python to 0.6.0
This allows us to build shopify_python on the new M1 Macbooks, and makes it compatible with the other repos that depend on it that are upgrading.
* Bump Python version
* Bumps mypy version
🎩  `dev up` runs successfully on M1 👍

M1 compatability fixes

---

requirements.txt
shopify_python/__init__.py

Leaving `astroid` to install an older version for Python 2 but install latest compatible available versions for Python 3.
The reasoning behind this is that pylint needs upgrading for Python 3.9+, which can't be done without updating astroid:
```
┃ The conflict is caused by:
┃     The user requested astroid<=2.1.0 and >=1.6.1
┃     pylint 2.12.2 depends on astroid<2.10 and >=2.9.0
```

M1 compatibility fixes: bump astroid version

---

setup.py
shopify_python/__init__.py

As a follow up to https://github.com/Shopify/shopify_python/pull/120, we can't install a more recent version of pylint as we specify it in `setup.py` - easy to miss as it's not in the requirements.
Tested by installing the wheel locally in required repo and then installing pylint

Pylint version in setup.py for Py3

---

dev.yml
requirements.txt
setup.py
shopify_python/__init__.py

Moving gitpython to 3.1.30 for python 3
also bumping local python from `3.9.7` to `3.9.8` for m1 compat reasons

Bumping gitpython for python3
